version: '3'

services:
  springer:
    image: dtr.rogfk.no/fint-beta/springer:3.11.2-2.7.0
    ports:
      - "9002:8080"
    environment:
      TZ: Europe/Oslo
      spring.data.mongodb.uri: mongodb://db:27017/springer
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - db

  db:
    image: mongo:3.4.4
    environment:
      TZ: Europe/Oslo
    volumes:
      - db-volume:/data/db
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  express:
    image: mongo-express
    ports:
      - "9009:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  adapter-personal:
    image: dtr.rogfk.no/fint-beta/springer-adapter-personal:3.11.0-2.7.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/response
    depends_on:
      - springer

  adapter-fullmakt:
    image: dtr.rogfk.no/fint-beta/springer-adapter-fullmakt:3.2.0-2.4.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/fullmakt/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/fullmakt/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/fullmakt/provider/response
    depends_on:
      - springer

  adapter-organisasjon:
    image: dtr.rogfk.no/fint-beta/springer-adapter-organisasjon:1.0.0-3
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/response
    depends_on:
      - springer

  adapter-administrasjon-kodeverk:
    image: dtr.rogfk.no/fint-beta/springer-adapter-administrasjon-kodeverk:3.5.0-2.6.0-rc-1
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/kodeverk/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/kodeverk/provider/response
    depends_on:
      - springer

  adapter-felles-kodeverk:
    image: dtr.rogfk.no/fint-beta/springer-adapter-felles-kodeverk:1.0.1-1
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: fint.felles.kodeverk
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/felles/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/felles/kodeverk/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/felles/kodeverk/provider/response
      logging.level.no.fint: DEBUG
    depends_on:
      - springer

  adapter-elev:
    image: dtr.rogfk.no/fint-beta/springer-adapter-elev:3.11.0-2.7.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/utdanning/elev/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/utdanning/elev/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/utdanning/elev/provider/response
      logging.level.no.fint.provider.springer.service: DEBUG
    depends_on:
      - springer

  adapter-utdanningsprogram:
    image: dtr.rogfk.no/fint-beta/springer-adapter-utdanningsprogram:3.10.0-2.7.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/utdanning/utdanningsprogram/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/utdanning/utdanningsprogram/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/utdanning/utdanningsprogram/provider/response
      logging.level.no.fint.provider.springer.service: DEBUG
    depends_on:
      - springer

  adapter-timeplan:
    image: dtr.rogfk.no/fint-beta/springer-adapter-timeplan:3.10.1-2.7.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/utdanning/timeplan/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/utdanning/timeplan/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/utdanning/timeplan/provider/response
      logging.level.no.fint.provider.springer.service: DEBUG
    depends_on:
      - springer

  adapter-vurdering:
    image: dtr.rogfk.no/fint-beta/springer-adapter-vurdering:3.7.0-2.6.0-rc-1
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/utdanning/vurdering/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/utdanning/vurdering/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/utdanning/vurdering/provider/response
      logging.level.no.fint.provider.springer.service: DEBUG
    depends_on:
      - springer

  adapter-utdanning-kodeverk:
    image: dtr.rogfk.no/fint-beta/springer-adapter-utdanning-kodeverk:3.8.0-2.6.0
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: Europe/Oslo
      fint.springer.base-url: "http://springer:8080"
      fint.adapter.organizations: pwf.no
      fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/utdanning/kodeverk/provider/sse/%s
      fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/utdanning/kodeverk/provider/status
      fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/utdanning/kodeverk/provider/response
    depends_on:
      - springer

volumes:
  db-volume:
