version: '3'

services:
  springer:
   image: fint/springer:latest
   ports:
     - "9002:8080"
   environment:
    TZ: Europe/Oslo
    springfox.title: "FINT Springer"
    spring.data.mongodb.uri: mongodb://db:27017/springer
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   networks:
    - fint_springer
   depends_on:
    - db

  db:
   image: mongo:3.4.4
   environment:
    TZ: Europe/Oslo
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   networks:
    - fint_springer

  adapter-personal:
   image: fint/springer-adapter:latest
   ports:
     - "9003:8080"
   environment:
    TZ: Europe/Oslo
    springfox.title: "FINT Springer Adapter Personal"
    fint.springer.base-url: "http://springer:8080"
    fint.adapter.organizations: pwf.no
    fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/sse/%s
    fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/status
    fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/personal/provider/response
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   networks:
    - fint_springer
   depends_on:
    - springer

  adapter-organisation:
   image: fint/springer-adapter-organisasjon:latest
   ports:
     - "9004:8080"
   environment:
    TZ: Europe/Oslo
    springfox.title: "FINT Springer Adapter Organisasjon"
    fint.springer.base-url: "http://springer:8080"
    fint.adapter.organizations: pwf.no
    fint.adapter.sse-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/sse/%s
    fint.adapter.status-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/status
    fint.adapter.response-endpoint: https://play-with-fint.felleskomponent.no/administrasjon/organisasjon/provider/response
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 1
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   networks:
    - fint_springer
   depends_on:
    - springer

networks:
 fint_springer:
  driver: overlay
  external: false
